[package]
description = "Create an HTML slide deck from Markdown"
edition = "2021"
license = "CC0-1.0"
name = "slidedeck"
version = "0.0.1"

[dependencies]
boilerplate = "1.0.0"
clap = { version = "3.1.18", features = ["derive"] }
html-escaper = "0.2.0"
pulldown-cmark = "0.9.3"
